server:
  port: 8008

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/find_hai
    username: postgres
    password: findhai
    hikari:
      maximum-pool-size: '10'
      connection-timeout: '60000'

ams:
  whonet-data-upload-url: https://findams.intellisoftkenya.com/
  funsoft:
    antibiotic-prescriptions-url: https://funsoft.systempartners.biz:17933/FunsoftWebServices/funsoft/ArraysService/getpatientsantibioticprescriptions?
    atc-ddd-index-url: https://www.whocc.no/atc_ddd_index/?code=
    daily-admissions-url: https://funsoft.systempartners.biz:17933/FunsoftWebServices/funsoft/ArraysService/getadmissions?
