server:
  port: 8008

ams:
  datastore-url: https://findams.intellisoftkenya.com/api/40/dataStore/tracker-capture
  whonet-data-upload-url: https://findams.intellisoftkenya.com/api/trackedEntityInstances
  trackedEntityAttributes-url: https://findams.intellisoftkenya.com/api/29/trackedEntityAttributes
  event-program-url: https://findams.intellisoftkenya.com/api/40/tracker?async=false
  dhis:
    username: admin
    password: district
  funsoft:
    amu-url: https://funsoft.systempartners.biz:17933/FunsoftWebServices/funsoft/ArraysService/getpatientsantibioticprescriptions?
    atc-ddd-index-url: https://www.whocc.no/atc_ddd_index/?code=
    amc-url: https://funsoft.systempartners.biz:17933/FunsoftWebServices/funsoft/ArraysService/getadmissions?
