server:
  port: 8008

ams:
  datastore-url: https://findams.intellisoftkenya.com/api/29/
  whonet-data-upload-url: https://findams.intellisoftkenya.com/api/trackedEntityInstances
  trackedEntityAttributes-url: https://findams.intellisoftkenya.com/api/29/trackedEntityAttributes
  dhis:
    username: admin
    password: district
  funsoft:
    antibiotic-prescriptions-url: https://funsoft.systempartners.biz:17933/FunsoftWebServices/funsoft/ArraysService/getpatientsantibioticprescriptions?
    atc-ddd-index-url: https://www.whocc.no/atc_ddd_index/?code=
    daily-admissions-url: https://funsoft.systempartners.biz:17933/FunsoftWebServices/funsoft/ArraysService/getadmissions?
